version: "2.3"
services:
  python-env:
    shm_size: 8gb
    build: 
      context: ./python-env-pytorch/
    image: cmy-penv:pytorch
    container_name: cmy-penv-docker
    hostname: penv-docker
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    runtime: nvidia # this is only supported in v2 not v3
    volumes:
      - type: bind
        source: /workspace/cmy
        target: /home/cmy
    working_dir: /home/cmy
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "10000:8888"
      - "10001:8443"
      - "10002:6006"