version: "2.3"
services:
  python-env:
    build: ./python-env-pytorch
    image: cmy-python-env:pytorch
    container_name: cmy-python-env-docker
    hostname: python-env-docker
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    runtime: nvidia # this is only supported in v2 not v3
    volumes:
      - type: bind
        source: /workspace/cmy
        target: /home/cmy
    working_dir: /home/cmy
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 114.114.114.114
    ports:
      - "10000:8888"
      - "10001:8443"