version: "2.3"
services:
  python-env:
    shm_size: 4gb
    build: 
      context: ../penv-mini/
    image: cava-penv-mini:latest
    container_name: cava-penv-docker
    hostname: penv-docker
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - /Users/cavallone/Desktop:/home/workspace

    working_dir: /home/workspace
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "10000:22" # ssh
      - "10001:8888" # jupyterlab
      - "10002:6006" # tensorboard