version: '3'
services:
    miniflux:
        image: miniflux/miniflux:latest
        restart: unless-stopped
        ports:
            - "8100:8080"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://miniflux:h6626068@db/miniflux?sslmode=disable
            - RUN_MIGRATIONS=1
            - CREATE_ADMIN=1
            - ADMIN_USERNAME=cavallone
            - ADMIN_PASSWORD=h6626068
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=miniflux
            - POSTGRES_PASSWORD=h6626068
        volumes:
            - miniflux-db:/var/lib/postgresql/data
volumes:
    miniflux-db: