version: '3'
services:
    v2ray:
        image: v2ray/official
        ports:
            - "16823:16823"
            - "11872:11872"
        volumes:
            - ./config.json:/etc/v2ray/config.json
        restart: always